# Generated by Django 3.2.7 on 2021-10-20 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Producto')),
                ('description', models.TextField(max_length=500, verbose_name='Descripcion del producto')),
                ('foto', models.ImageField(null=True, upload_to='Inventario', verbose_name='Agregar imagen')),
            ],
            options={
                'verbose_name': 'Nuevo Producto a Inventario',
                'verbose_name_plural': 'Nuevos Productos a Inventario',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('perecedero', models.BooleanField(default=False, verbose_name='¿Es Perecedero?')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product', verbose_name='Seleccione el producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
            },
        ),
    ]
