# Generated by Django 3.2.7 on 2021-10-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='foto',
            field=models.ImageField(null=True, upload_to='imgProducts', verbose_name='Agregar imagen'),
        ),
    ]
