# Generated by Django 3.2.7 on 2021-11-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Proveedor')),
                ('direccion', models.CharField(max_length=100, unique=True, verbose_name='Dirección')),
            ],
        ),
    ]
