# Generated by Django 3.2.7 on 2021-11-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
